import cron from 'node-cron';
import axios from 'axios';
import prisma from '../lib/prisma.js';
import { sendAlertEmail } from '../lib/mailer.js';

const VICTORIA_METRICS_URL = process.env.INTERNAL_VICTORIA_METRICS_URL || 'http://victoriametrics:8428';

/**
 * Build a PromQL query for the given metric, optionally scoped to a specific instance.
 */
function buildQuery(metric, instanceTarget) {
  const f = instanceTarget ? `instance=~".*${instanceTarget}.*"` : '';

  switch (metric) {
    case 'cpu':
      return f
        ? `max((100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle",${f}}[5m])) * 100)) or (100 - (avg by (instance) (rate(windows_cpu_time_total{mode="idle",${f}}[5m])) * 100)))`
        : `max((100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) or (100 - (avg by (instance) (rate(windows_cpu_time_total{mode="idle"}[5m])) * 100)))`;

    case 'memory':
      return f
        ? `max((100 - ((node_memory_MemAvailable_bytes{${f}} / node_memory_MemTotal_bytes{${f}}) * 100)) or ((1 - (windows_memory_available_bytes{${f}} / windows_memory_physical_total_bytes{${f}})) * 100))`
        : `max((100 - ((node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100)) or ((1 - (windows_memory_available_bytes / windows_memory_physical_total_bytes)) * 100))`;

    case 'disk':
      return f
        ? `max((100 - ((node_filesystem_avail_bytes{mountpoint="/",fstype!="tmpfs",${f}} / node_filesystem_size_bytes{mountpoint="/",fstype!="tmpfs",${f}}) * 100)) or (100 - ((windows_logical_disk_free_bytes{volume!~"HarddiskVolume.*",${f}} / windows_logical_disk_size_bytes{volume!~"HarddiskVolume.*",${f}}) * 100)))`
        : `max((100 - ((node_filesystem_avail_bytes{mountpoint="/",fstype!="tmpfs"} / node_filesystem_size_bytes{mountpoint="/",fstype!="tmpfs"}) * 100)) or (100 - ((windows_logical_disk_free_bytes{volume!~"HarddiskVolume.*"} / windows_logical_disk_size_bytes{volume!~"HarddiskVolume.*"}) * 100)))`;

    default:
      return null;
  }
}

/**
 * Resolve the prometheus `instance` target (IP:port) for a given DB instance record ID.
 */
async function resolveInstanceTarget(dbInstanceId) {
  if (!dbInstanceId || dbInstanceId === 'ALL') return null;

  try {
    const inst = await prisma.monitoredInstance.findUnique({
      where: { id: dbInstanceId },
      select: { privateIp: true, publicIp: true, exporterPort: true, instanceId: true }
    });

    if (!inst) return null;

    const ip = inst.privateIp || inst.publicIp;
    if (ip) return ip;
    return inst.instanceId || null;
  } catch (e) {
    console.error('Failed to resolve instance target:', e.message);
    return null;
  }
}

/**
 * Build a beautiful HTML email body for an alert
 */
function buildEmailHtml(rule, metricLabel, value, orgName) {
  const severityColor = value > rule.threshold + 20 ? '#ef4444' : '#f97316';
  const intervalLabel = formatIntervalLabel(rule.repeatInterval || 300);
  return `
    <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;background:#0f172a;color:#e2e8f0;border-radius:12px;overflow:hidden">
      <div style="background:${severityColor};padding:20px 24px">
        <h1 style="margin:0;font-size:20px;color:#fff">🚨 Sidroid Alert: ${metricLabel} Threshold Exceeded</h1>
      </div>
      <div style="padding:24px">
        <p style="color:#94a3b8;font-size:14px;margin:0 0 16px">An alert threshold has been crossed in your monitored infrastructure.</p>
        <table style="width:100%;border-collapse:collapse;font-size:14px">
          <tr><td style="padding:8px 0;color:#64748b;width:140px">Organization</td><td style="padding:8px 0;font-weight:600">${orgName || 'N/A'}</td></tr>
          <tr><td style="padding:8px 0;color:#64748b">Metric</td><td style="padding:8px 0;font-weight:600">${metricLabel}</td></tr>
          <tr><td style="padding:8px 0;color:#64748b">Current Value</td><td style="padding:8px 0;font-weight:700;color:${severityColor};font-size:18px">${value.toFixed(2)}%</td></tr>
          <tr><td style="padding:8px 0;color:#64748b">Threshold Set</td><td style="padding:8px 0">${rule.threshold}%</td></tr>
          <tr><td style="padding:8px 0;color:#64748b">Instance</td><td style="padding:8px 0">${rule.instanceId === 'ALL' ? 'All Instances' : rule.instanceId}</td></tr>
          <tr><td style="padding:8px 0;color:#64748b">Alert Frequency</td><td style="padding:8px 0">Every ${intervalLabel}</td></tr>
          <tr><td style="padding:8px 0;color:#64748b">Triggered At</td><td style="padding:8px 0">${new Date().toLocaleString()}</td></tr>
        </table>
        <div style="margin-top:24px;padding:16px;background:#1e293b;border-radius:8px;border-left:4px solid ${severityColor}">
          <p style="margin:0;font-size:13px;color:#94a3b8">This alert was generated by the <strong style="color:#e2e8f0">Sidroid Custom Alert Engine</strong>. Log in to your dashboard to investigate.</p>
        </div>
      </div>
    </div>
  `;
}

/**
 * Convert seconds to a human-readable label for emails
 */
function formatIntervalLabel(seconds) {
  if (seconds < 60) return `${seconds} seconds`;
  if (seconds < 3600) return `${Math.floor(seconds / 60)} minute(s)`;
  return `${Math.floor(seconds / 3600)} hour(s)`;
}

// Per-rule cooldown tracker: ruleId -> timestamp of last fired email (ms)
const lastFiredMap = new Map();

export function startAlertEvaluator() {
  console.log('✅ Starting Sidroid Custom Alert Evaluator (runs every 20 seconds, per-rule cooldown)');

  // Run every 20 seconds using 6-field cron syntax (seconds support)
  cron.schedule('*/20 * * * * *', async () => {
    try {
      const rules = await prisma.alertRule.findMany({
        where: {
          isActive: true,
          alertType: { in: ['CUSTOM', 'BOTH'] }
        },
        include: { organization: true }
      });

      if (!rules.length) return;

      for (const rule of rules) {
        // Per-rule cooldown check based on user-configured repeatInterval (default 300s)
        const cooldownMs = (rule.repeatInterval || 300) * 1000;
        const lastFired = lastFiredMap.get(rule.id);
        const now = Date.now();

        if (lastFired && now - lastFired < cooldownMs) {
          // Still in cooldown — skip evaluation entirely for this rule
          continue;
        }

        // Resolve actual prometheus instance label (IP:port)
        const instanceTarget = await resolveInstanceTarget(rule.instanceId);
        const query = buildQuery(rule.metric, instanceTarget);

        if (!query) {
          console.warn(`[AlertEvaluator] Unknown metric "${rule.metric}" for rule ${rule.id}`);
          continue;
        }

        try {
          const res = await axios.get(`${VICTORIA_METRICS_URL}/api/v1/query`, {
            params: { query },
            timeout: 8000
          });

          const results = res.data?.data?.result || [];

          if (results.length === 0) {
            console.log(`[AlertEvaluator] Rule ${rule.id} (${rule.metric}): No metrics data yet.`);
            continue;
          }

          // Take the max value across all matched instances
          let maxValue = -Infinity;
          for (const r of results) {
            const v = parseFloat(r.value[1]);
            if (!isNaN(v) && v > maxValue) maxValue = v;
          }

          console.log(`[AlertEvaluator] ${rule.metric.toUpperCase()} = ${maxValue.toFixed(2)}% (threshold: ${rule.threshold}%, interval: ${formatIntervalLabel(rule.repeatInterval || 300)})`);

          if (maxValue > rule.threshold) {
            // Mark this rule as fired NOW (before sending — prevents race conditions)
            lastFiredMap.set(rule.id, now);

            const metricLabel = { cpu: 'CPU Usage', memory: 'Memory Usage', disk: 'Disk Usage' }[rule.metric] || rule.metric;
            const alertMsg = `${metricLabel} is at ${maxValue.toFixed(2)}% — exceeds threshold of ${rule.threshold}%`;
            console.log(`[ALERT 🚨] ${alertMsg} | Org: ${rule.organization?.name} | Next alert in: ${formatIntervalLabel(rule.repeatInterval || 300)}`);

            // Save alert to DB
            try {
              await prisma.alert.create({
                data: {
                  organizationId: rule.organizationId,
                  title: `${metricLabel} Threshold Exceeded`,
                  description: alertMsg,
                  severity: 'HIGH',
                  source: 'SIDROID_CUSTOM_ENGINE',
                  metricName: rule.metric,
                  instanceId: rule.instanceId === 'ALL' ? null : rule.instanceId,
                  status: 'OPEN',
                }
              });
            } catch (dbErr) {
              console.error('[AlertEvaluator] DB save failed:', dbErr.message);
            }

            // Send Emails
            if (rule.emails) {
              const emailList = rule.emails.split(',').map(e => e.trim()).filter(Boolean);
              for (const email of emailList) {
                const subject = `[Sidroid 🚨] High ${metricLabel} — ${maxValue.toFixed(1)}% (Threshold: ${rule.threshold}%)`;
                const text = alertMsg;
                const html = buildEmailHtml(rule, metricLabel, maxValue, rule.organization?.name);
                await sendAlertEmail(email, subject, text, html);
              }
            }
          }
        } catch (e) {
          console.error(`[AlertEvaluator] Failed to evaluate rule ${rule.id}:`, e.message);
        }
      }
    } catch (error) {
      console.error('[AlertEvaluator] Cron error:', error.message);
    }
  });
}
