global:
  scrape_interval: 15s
  external_labels:
    monitoring_stack: sidroid-multi-org

scrape_configs:
  - job_name: victoriametrics
    static_configs:
      - targets: ["victoriametrics:8428"]
        labels:
          organization_id: "platform"
          organization_name: "MonitoringPlatform"
          service: "victoriametrics"
          node: "victoriametrics"

  - job_name: vmagent
    static_configs:
      - targets: ["vmagent:8429"]
        labels:
          organization_id: "platform"
          organization_name: "MonitoringPlatform"
          service: "vmagent"
          node: "vmagent"

  - job_name: aws-ec2-node-exporter
    scrape_interval: 15s
    ec2_sd_configs:
      - region: us-east-1
        port: 9100

    relabel_configs:
      - source_labels: [__meta_ec2_tag_Monitor]
        regex: true
        action: keep

      - source_labels: [__meta_ec2_instance_state]
        regex: running
        action: keep

      - source_labels: [__meta_ec2_public_ip]
        regex: (.+)
        target_label: __address__
        replacement: ${1}:9100

      - source_labels: [__meta_ec2_tag_OrgId]
        target_label: organization_id

      - source_labels: [__meta_ec2_tag_OrgName]
        target_label: organization_name

      - source_labels: [__meta_ec2_tag_Service]
        target_label: service

      - source_labels: [__meta_ec2_tag_Node]
        target_label: node

      - source_labels: [__meta_ec2_instance_id]
        target_label: aws_instance_id

      - source_labels: [__meta_ec2_public_ip]
        target_label: aws_public_ip

      - source_labels: [__meta_ec2_private_ip]
        target_label: aws_private_ip

      - source_labels: [__meta_ec2_availability_zone]
        target_label: aws_az

  - job_name: 'sidroid-dynamic-instances'
    scrape_interval: 15s
    http_sd_configs:
      - url: 'http://cloud-ventur-backend:5000/api/instances/sd-targets'