apiVersion: 1
policies:
  - orgId: 1
    receiver: email-receiver
    group_by: ['grafana_folder', 'alertname']
    routes:
      - receiver: email-receiver
        object_matchers:
          - ['severity', '=', 'critical']
